---
- hosts: ubuntu-ec2
  tasks:
    - name: ping user
      ping:
    - name: APT works with the https
      become: yes
      become_user: root
      apt: name=apt-transport-https update_cache=yes state=present
    - name: install CA certificates
      become: yes
      become_user: root
      apt: name=ca-certificates update_cache=yes state=present
    - name: Add GPG
      become: yes
      become_user: root
      shell: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    - name:  Add Ubuntu operating system entry
      become: yes
      become_user: root
      shell: echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" > /etc/apt/sources.list.d/docker.list creates=/etc/apt/sources.list.d/docker.list
    # - name: Purge the old repo
    #   become: yes
    #   become_user: root
    #   apt: name=lxc-docker purge=yes
    - name: Verify  APT pulling from the right repository
      become: yes
      become_user: root
      shell: apt-cache policy docker-engine
    - name: Install recommended package
      become: yes
      become_user: root
      apt: name=linux-image-extra-3.13.0-86-generic force=yes state=present update_cache=yes
    - name: Install Apparmor
      become: yes
      become_user: root
      apt: name=apparmor update_cache=yes
    - name: Install Docker engine
      become: yes
      become_user: root
      apt: name=docker-engine force=yes state=present update_cache=yes
    - name: Add ubuntu user to docker group
      become: yes
      become_user: root
      user: name=ubuntu groups=docker append=yes
    - name: Copy dockerfile and other files to build image
      synchronize: src=./docker/ dest=/home/ubuntu/docker set_remote_user=yes
    - name: install pip
      become: yes
      become_user: root
      apt: name=python-pip
    - name: install docker-py
      become: yes
      become_user: root
      pip: name=docker-py
    - name: build docker image
      docker_image: path="/home/ubuntu/docker" name="tahaderouiche/jenkins" tag="version2.2" state=present
    - name: run docker
      docker:
        name: jenkins
        image: tahaderouiche/jenkins:version2.2
        ports: 0.0.0.0:8081:8080 , 0.0.0.0:5000:5000
        state: started
        volumes: /var/jenkins_home



