---
- hosts: dockerhost
  tasks:
    - name: Run Jenkins container
      become: yes
      docker:
        name: myjenkins
        image: my_jenkins_image
        ports: 0.0.0.0:8081:8080 , 0.0.0.0:5000:5000
        state: started
        volumes: /var/jenkins_home
        volumes_from: myjenkinsdata
