---
- name: Configure webserver with nginx
  hosts: dockerhost
#  sudo: True
  tasks:
    - name: ping user
      ping:
    - name: Show admin password
      shell: docker exec -it jenkins cat /var/jenkins_home/secrets/initialAdminPassword
      register: password
    - debug:  msg="Administrator password {{ password.stdout }}"

