---

    - name: ping user
      ping:
    - name: APT works with the https
      become: yes
      become_user: root
      apt: name=apt-transport-https update_cache=yes state=present
    - name: Install CA certificates
      become: yes
      become_user: root
      apt: name=ca-certificates update_cache=yes state=present
    - name: Add GPG
      become: yes
      become_user: root
      shell: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    - name:  Add Ubuntu operating system entry
      become: yes
      become_user: root
      shell: echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" > /etc/apt/sources.list.d/docker.list creates=/etc/apt/sources.list.d/docker.list
    - name: Verify  APT pulling from the right repository
      become: yes
      become_user: root
      shell: apt-cache policy docker-engine
    - name: Install recommended package
      become: yes
      become_user: root
      apt: name=linux-image-extra-3.13.0-86-generic force=yes state=present update_cache=yes
    - name: Install Apparmor
      become: yes
      become_user: root
      apt: name=apparmor update_cache=yes
    - name: Install Docker engine
      become: yes
      become_user: root
      apt: name=docker-engine force=yes state=present update_cache=yes
    - name: Add host user to docker group
      become: yes
      become_user: root
      user: name={{ ansible_ssh_user }} groups=docker append=yes
    - name: Copy dockerfile and other files to build image
      synchronize: src=./docker/ dest={{ dockerfilespath }}/docker set_remote_user=yes perms=yes
    - name: Copy Data container dockerfile
      synchronize: src=./jenkins_data/ dest={{ dockerfilespath }}/jenkins_data set_remote_user=yes perms=yes
    - name: Install pip
      become: yes
      become_user: root
      apt: name=python-pip
    - name: Install docker-py
      become: yes
      become_user: root
      pip: name=docker-py
