---
    - name: build docker image
      become: yes
      become_user: root
      docker_image: path="{{ dockerfilespath }}/docker" name="tahaderouiche/jenkins" tag="version2.2"
    - name: run docker
      become: yes
      docker:
        name: jenkinsv2.2
        image: tahaderouiche/jenkins:version2.2
        ports: 0.0.0.0:8081:8080 , 0.0.0.0:5000:5000
        state: started
        volumes: /var/jenkins_home
